# Generated by Django 4.0.6 on 2022-08-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('image', models.ImageField(default='', upload_to='prop/images')),
            ],
        ),
    ]
