# Generated by Django 4.0.6 on 2022-09-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
