# Generated by Django 4.0.6 on 2022-09-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_product_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popu',
            field=models.BooleanField(default=False),
        ),
    ]
