# Generated by Django 4.0.6 on 2022-09-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_product_popu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='popularity',
        ),
    ]
